/**
 * Swagger Service
 * Data Service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface CartArticle {
    articleByIdArticle?: models.CartArticleArticleByIdArticle;

    cartByIdCart?: models.CartArticleCartByIdCart;

    idArticle?: number;

    idCart?: number;

    quantity?: number;

}
