/**
 * Swagger Service
 * Data Service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface InlineResponse2004 {
    $Schema?: string;

    definitions?: { [key: string]: models.InlineResponse2004Definitions; };

    description?: string;

    properties?: { [key: string]: models.InlineResponse2004Properties; };

    requiredProperties?: any;

    title?: string;

    type?: string;

}
